IS4Workspace/IS4Server/ViewModels/WebAPIResources.cs
using IdentityServer4.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IS4Server.ViewModels
{
    public class WebAPIResources 
    {
        public string Name { get; set; }

        [Display(Name="Display Name")]
        public string DisplayName { get; set; }
        
        public string Scope { get; set; }
        
    }
}

IS4Workspace/IS4Server/ViewModels/WebClients.cs
using IdentityServer4.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace IS4Server.ViewModels
{
    public class WebClients
    {
        [Required]
        public string ClientId { get; set; }

        [Display(Name = "Client Name")]
        public string ClientName { get; set; }

        [Display(Name = "Client Secret")]
        public string ClientSecret { get; set; }

        [Required]
        [Display(Name = "Client Scope")]
        public string ClientScope { get; set; } 
    }
}

IS4Workspace/IS4Server/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using IS4Server.ViewModels;
using IS4Server.Config;
using Newtonsoft.Json;

namespace IS4Server.Controllers
{
    public class ClientController : Controller
    {
        const string ClientKey = "ClientSession";
        // GET: Client
        public ActionResult Index()
        {
            try
            {
                var str = HttpContext.Session.GetString(ClientKey);
                var obj = JsonConvert.DeserializeObject<WebClients>(str);
                return View(obj);
            }
            catch (Exception) { return View(); }
            
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebClients webClients)
        {
            Clients clients = new Clients();
            clients.SetClients(webClients.ClientId, webClients.ClientName, webClients.ClientSecret, webClients.ClientScope);

            var jsonString = JsonConvert.SerializeObject(webClients);
            HttpContext.Session.SetString(ClientKey, jsonString);
            
            return View();
            
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Client/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Client/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IS4Workspace/IS4Server/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IS4Server.Config;

namespace IS4Server.Controllers
{
    public class HomeController : Controller
    {   
        public IActionResult Index()
        {            
            return View();
        }        

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

IS4Workspace/IS4Server/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using IS4Server.ViewModels;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using IS4Server.Config;
using Newtonsoft.Json;

namespace IS4Server.Controllers
{
    public class ResourceController : Controller
    {
        private const string ResourceKey = "ResourceSession";

        // GET: Resource
        public ActionResult Index()
        {
            try
            {
                var str = HttpContext.Session.GetString(ResourceKey);
                var obj = JsonConvert.DeserializeObject<WebAPIResources>(str); 
                return View(obj);
            }
            catch (Exception) { return View(); }
        }

        // GET: Resource/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Resource/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Resource/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebAPIResources _resources)  
        {
            Resources res = new Resources();
            res.SetApiResources(_resources.Name, _resources.DisplayName, _resources.Scope);

            var jsonString = JsonConvert.SerializeObject(_resources);
            HttpContext.Session.SetString(ResourceKey, jsonString);

            return View();
        }

        // GET: Resource/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Resource/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Resource/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Resource/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

IS4Workspace/IS4Server/Views/Client/Create.cshtml
@model IS4Server.ViewModels.WebClients

@{
    ViewData["Title"] = "Add Client";
    <script src="~/Scripts/ClientJS.js"></script>
}

<h2 style="text-align:center">Add Client</h2>

<form asp-action="Create">
    
    <div class="alert alert-danger alert-dismissable fade in" id="clientErrorMessage" hidden></div>

    <br />
    <div class="row">
        <h4>Client Details</h4>
        <hr />

        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ClientId" class="control-label"></label>
            </div>
            <div class="col-sm-8">
                <input asp-for="ClientId" class="form-control" id="ClientId" />
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ClientName" class="control-label"></label>
            </div>
            <div class="col-sm-8">
                <input asp-for="ClientName" class="form-control" id="ClientName" />
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ClientSecret" class="control-label"></label>
            </div>
            <div class="col-sm-8">
                <input asp-for="ClientSecret" class="form-control" id="ClientSecret" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ClientScope" class="control-label"></label>
            </div>
            <div class="col-sm-8">
                <input asp-for="ClientScope" class="form-control" id="ClientScope" />
            </div>
        </div>
        <br />


        <div class="row">
            <div class="col-sm-4">
                <a class="btn btn-default" onclick="clearClient()">Clear</a>
            </div>

            <div class="col-sm-4" style="text-align:center">
                <a href="Index" class="btn btn-default">Cancel</a>
            </div>

            <div class="col-sm-4" style="text-align:right">
                <input type="submit" value="Save" class="btn btn-default" onclick="return validateClientInput();" />

            </div>

        </div>


    </div>
</form>

IS4Workspace/IS4Server/Views/Client/Delete.cshtml
@{
    ViewData["Title"] = "Delete Client";
}

<h2 style="text-align:center">Delete Client</h2>
<br />
<h4 style="text-align:center">Are you sure you want to delete this?</h4>

<form>

    <div class="row">

        <div class="col-sm-3">
            <p class="page-header">Client  Details</p>
            <label>Name: </label> <label></label> <br />
            <label>Display Name: </label> <label></label> <br />
            <label>Description: </label> <label></label> <br />

            <label>Status: </label> <label></label>
            <br />
            <p class="page-header">Application URI</p>
            <label>Redirect URI: </label> <label></label> <br />
            <label>Logout URI: </label> <label></label> <br />

        </div>

        <div class="col-sm-2">
            <p class="page-header">Scopes</p>
        </div>

        <div class="col-sm-2">
            <p class="page-header">Secrets</p>
        </div>

        <div class="col-sm-2">
            <p class="page-header">Claims</p>
        </div>

        <div class="col-sm-2">
            <p class="page-header">Resources</p>
        </div>
    </div>
    <br />


    <div class="row">
        <div class="col-sm-6">
            <a href="Index" class="btn btn-default" style="background-color:gainsboro">Cancel</a>
        </div>

        <div class="col-sm-6" style="text-align:right;">
            <input type="submit" value="Delete" id="btnDelete" class="btn" />
        </div>

    </div>

</form>

IS4Workspace/IS4Server/Views/Client/Details.cshtml
@{
    ViewData["Title"] = "Client Details";
}

<h2 style="text-align:center">Client Details</h2>


<div class="row">

    <div class="col-sm-3">
        <p class="page-header">Client  Details</p>
        <label>Name: </label> <label></label> <br />
        <label>Display Name: </label> <label></label> <br />
        <label>Description: </label> <label></label> <br />

        <label>Status: </label> <label></label>
        <br />
        <p class="page-header">Application URI</p>
        <label>Redirect URI: </label> <label></label> <br />
        <label>Logout URI: </label> <label></label> <br />

    </div>

    <div class="col-sm-2">
        <p class="page-header">Scopes</p>
    </div>

    <div class="col-sm-2">
        <p class="page-header">Secrets</p>
    </div>

    <div class="col-sm-2">
        <p class="page-header">Claims</p>
    </div>

    <div class="col-sm-2">
        <p class="page-header">Resources</p>
    </div>
</div>
<br />

<div class="row">
    <div class="col-sm-6">
        <a href="Index" class="btn btn-default" style="background-color:gainsboro">Back</a>
    </div>

    <div class="col-sm-6" style="text-align:right">
        <a href="Edit" class="btn btn-default" style="background-color:gainsboro">Edit</a>
    </div>

</div>

IS4Workspace/IS4Server/Views/Client/Index.cshtml
@model  IS4Server.ViewModels.WebClients
 

@{
    ViewData["Title"] = "Clients";

    <script>
    $(document).ready(function () {
        $("#clientsTable").DataTable();
    });
    </script>

    <style>
        .glyphicon {
            width: 30px;
        }
       
    </style>

}

<h2 style="text-align:center">Clients</h2>

<table id="clientsTable">
    <thead>
        <tr>
            <th>Client ID</th>
            <th>Client Name</th>
            <th>Client Secret</th>
            <th>Client Scope</th>
        </tr>
    </thead>

    <tbody>  
        
        @{
            try {
                    <tr>
                        <td>@Model.ClientId </td>
                        <td>@Model.ClientName </td>
                        <td>@Model.ClientSecret </td>
                        <td>@Model.ClientScope </td>
                    </tr>
            }
            catch (Exception)
            {
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            }
        }

    </tbody>
</table>

IS4Workspace/IS4Server/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IS4Workspace/IS4Server/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IS4Workspace/IS4Server/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>*@



<br /><br /><br />
<div class="row">

    <div class="col-sm-3"></div>
    <div class="col-sm-3">
        <img src="~/images/logo.png" />
    </div>
    <div class="col-sm-3"></div>


</div>

IS4Workspace/IS4Server/Views/Resource/Create.cshtml
@model IS4Server.ViewModels.WebAPIResources

@{
    ViewData["Title"] = "Add Resource";    
    <script src="~/Scripts/ResourceJS.js"></script>
}

<form asp-action="Create">

    <h2 style="text-align:center">Add Resource</h2>

    <div class="alert alert-danger alert-dismissable fade in" id="resourceErrorMessage" hidden></div>
    <br />
    <div class="row">
        <h4>Resource Details</h4>
        <hr />
        
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Name" class="control-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="Name" class="form-control" id="Name" />
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="DisplayName" class="control-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="DisplayName" class="form-control" id="DisplayName" />
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Scope" class="control-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="Scope" class="form-control" id="Scope" />
                </div>
            </div>
            <br />


            <div class="row">
                <div class="col-sm-4">
                    <a class="btn btn-default" onclick="clearResource()">Clear</a>
                </div>

                <div class="col-sm-4" style="text-align:center">
                    <a href="Index" class="btn btn-default" >Cancel</a>
                </div>

                <div class="col-sm-4" style="text-align:right">
                    <input type="submit" value="Save" class="btn btn-default" onclick="return validateInput();" />

                </div>

            </div>

    </div>

</form>

IS4Workspace/IS4Server/Views/Resource/Delete.cshtml
@{
    ViewData["Title"] = "Delete Resource";
}

<h2 style="text-align:center">Delete Resource</h2>
<br />
<h4 style="text-align:center">Are you sure you want to delete this?</h4>
<form>

    <div class="row">

        <div class="col-sm-3">
            <p class="page-header">Resource  Details</p>
            <label>Name: </label> <label></label> <br />
            <label>Display Name: </label> <label></label> <br />
            <label>Description: </label> <label></label> <br />
            <label>Status: </label> <label></label>

        </div>

        <div class="col-sm-3">
            <p class="page-header">Scopes</p>
        </div>

        <div class="col-sm-3">
            <p class="page-header">Secrets</p>
        </div>

        <div class="col-sm-3">
            <p class="page-header">Claims</p>
        </div>
    </div>
    <br />

    <div class="row">
        <div class="col-sm-6">
            <a href="Index" class="btn btn-default" style="background-color:gainsboro">Cancel</a>
        </div>

        <div class="col-sm-6" style="text-align:right;">
            <input type="submit" value="Delete" id="btnDelete" class="btn" />
        </div>

    </div>

</form>

IS4Workspace/IS4Server/Views/Resource/Details.cshtml
@{
    ViewData["Title"] = "Resource Details";
}

<h2 style="text-align:center">Resource Details</h2>

<div class="row">

    <div class="col-sm-3">
        <p class="page-header">Resource  Details</p>
        <label>Name: </label> <label></label> <br />
        <label>Display Name: </label> <label></label> <br />
        <label>Description: </label> <label></label> <br />
        <label>Status: </label> <label></label> 

    </div>

    <div class="col-sm-3">
        <p class="page-header">Scopes</p>
    </div>

    <div class="col-sm-3">
        <p class="page-header">Secrets</p>
    </div>

    <div class="col-sm-3">
        <p class="page-header">Claims</p>
    </div>
</div>
<br />

<div class="row">
    <div class="col-sm-6">
        <a href="Index" class="btn btn-default" style="background-color:gainsboro">Back</a>
    </div>

    <div class="col-sm-6" style="text-align:right">
        <a href="Edit" class="btn btn-default" style="background-color:gainsboro">Edit</a>
    </div>

</div>

IS4Workspace/IS4Server/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IS4Server</title>

    <environment names="Development">
        <script src="~/js/jquery-3.1.1.js" asp-append-version="true"></script>
        <script src="~/js/jquery.dataTables.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-switch.js" asp-append-version="true"></script>

    </environment>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="~/css/bootstrap-switch.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IS4Server</a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="nav navbar-nav navbar-right">

                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Clients
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Client" asp-action="Create">Add Clients</a></li>
                                <li><a asp-area="" asp-controller="Client" asp-action="Index">View Clients</a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Resources
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Resource" asp-action="Create">Add Resources</a></li>
                                <li><a asp-area="" asp-controller="Resource" asp-action="Index">View Resources</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - IS4Server</p>
        </footer>
    </div>


    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>